const config = require('./docusaurus.config');
const { sidebarsNavModules } = require('@commitdev/zero-doc-site-common-elements');

module.exports = {
  sidebar: [
    {
      "About": [
        {
          type: 'autogenerated',
          dirName: 'about',
        },
      ],
      "Components & References": [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
      "Guides": [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    sidebarsNavModules(config),
  ]
}